import { LegalPage } from "@/components/legal-page";

export default function TermsPage() {
  return (
    <LegalPage title="Terms of Service" updated="August 31, 2026">
      <p>
        These Terms of Service (&quot;Terms&quot;) govern your access to and use of RigMaintenance
        (the &quot;Service&quot;), operated by RigMaintenance (&quot;we,&quot; &quot;us,&quot; or
        &quot;our&quot;). By creating an account or using the Service, you agree to these Terms. If
        you are using the Service on behalf of a company, you are agreeing on that company&apos;s
        behalf and confirming you have the authority to do so.
      </p>

      <h2>1. What the Service Is</h2>
      <p>
        RigMaintenance is a record-keeping tool for tracking equipment inventory, maintenance
        schedules, and inspection checklists for fleet vehicles and trailers. It helps you organize
        and store your own inspection and maintenance records in one place.
      </p>

      <h2>2. Not a Substitute for Compliance Judgment</h2>
      <p>
        RigMaintenance is a documentation and reminder tool only. It does not perform inspections,
        certify compliance, or guarantee that your equipment meets DOT, ADA, or any other regulatory
        requirement. You remain solely responsible for ensuring your vehicles, equipment, and
        operations actually comply with all applicable laws and regulations. Checklist templates,
        reminders, and reports generated by the Service are aids, not legal or regulatory advice.
      </p>

      <h2>3. Accounts</h2>
      <p>
        You must provide accurate information when creating an account and are responsible for
        maintaining the security of your login credentials. You are responsible for all activity
        that happens under your account, including actions taken by technicians you invite to your
        company&apos;s account. Notify us promptly at support@rigmaintenance.net if you suspect
        unauthorized access.
      </p>

      <h2>4. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service for any unlawful purpose or to store data you don&apos;t have the right to store</li>
        <li>Attempt to gain unauthorized access to another company&apos;s data or accounts</li>
        <li>Interfere with or disrupt the Service&apos;s operation or security</li>
        <li>Reverse engineer or resell the Service without our written permission</li>
      </ul>

      <h2>5. Your Data</h2>
      <p>
        You own the data you enter into RigMaintenance — your unit records, inventory, checklists,
        inspection logs, and photos. We don&apos;t claim ownership over it. We store and process it
        on your behalf so you can use the Service, as described in our{" "}
        <a href="/privacy" className="text-navy-700 underline">
          Privacy Policy
        </a>
        . You&apos;re responsible for the accuracy of the data you and your technicians enter.
      </p>

      <h2>6. Subscriptions and Payment</h2>
      <p>
        Some features of the Service may require a paid subscription. Where applicable, pricing,
        billing frequency, and cancellation terms will be presented to you before you&apos;re
        charged. Fees are non-refundable except where required by law.
      </p>

      <h2>7. Termination</h2>
      <p>
        You may stop using the Service and close your account at any time by contacting us. We may
        suspend or terminate accounts that violate these Terms or that we reasonably believe pose a
        security risk to the Service or other users. On termination, we&apos;ll provide a reasonable
        opportunity to export your data unless legally prohibited from doing so.
      </p>

      <h2>8. Disclaimer of Warranties</h2>
      <p>
        THE SERVICE IS PROVIDED &quot;AS IS&quot; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
        IMPLIED, INCLUDING WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR
        NON-INFRINGEMENT. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR
        THAT IT WILL PREVENT ANY REGULATORY VIOLATION, ACCIDENT, OR EQUIPMENT FAILURE.
      </p>

      <h2>9. Limitation of Liability</h2>
      <p>
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, RIGMAINTENANCE SHALL NOT BE LIABLE FOR ANY INDIRECT,
        INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF DATA, REVENUE, OR
        PROFITS, ARISING FROM YOUR USE OF THE SERVICE — INCLUDING DAMAGES RELATED TO REGULATORY
        NON-COMPLIANCE, EQUIPMENT FAILURE, OR MISSED MAINTENANCE — EVEN IF ADVISED OF THE
        POSSIBILITY OF SUCH DAMAGES. OUR TOTAL LIABILITY FOR ANY CLAIM RELATED TO THE SERVICE WILL
        NOT EXCEED THE AMOUNT YOU PAID US IN THE 12 MONTHS BEFORE THE CLAIM AROSE.
      </p>

      <h2>10. Changes to These Terms</h2>
      <p>
        We may update these Terms from time to time. If we make material changes, we&apos;ll notify
        you by email or through the Service before they take effect. Continued use of the Service
        after changes take effect means you accept the updated Terms.
      </p>

      <h2>11. Governing Law</h2>
      <p>
        These Terms are governed by the laws of the State of Texas, without regard to its conflict
        of law principles.
      </p>

      <h2>12. Contact</h2>
      <p>Questions about these Terms? Reach us at support@rigmaintenance.net.</p>
    </LegalPage>
  );
}
